### ISSUE TITLE
容器bridge网络模式下，端口映射问题

### ISSUE THREAD

**Issue by nonight89** [xuxueli/xxl-rpc#11]
在使用xxl-job时，executor部署在docker上，容器端口与映射到机器端口不一致，从而导致executor没法注册上外部可访问的地址，比如容器里面rpc开启端口为9999，实际被映射到机器端口31520，外部访问得从31520端口才能访问到容器内部端口为9999的服务。
executor可以读取rpc服务映射的机器端口，但是rpc框架没有支持这种注册方式的接口，代码层面上也没有提供注册功能的扩展接口。
请问一下能帮忙解决一下吗，谢谢。

**Comment by xuxueli** [comment]
你好，可以考虑通过 “-p 9999:9999” 参数进行端口映射。

**Comment by xuxueli** [comment]
你好，迭代中的新版本新增了如下特性，可以借助该特性解决你的问题。

```
RPC Server端，新增属性 ”注册地址/registryAddress“，优先使用该属性作为注册地址，为空时使用服务 ”IP:PORT“ 作为注册地址。从而更灵活的支持容器类型执行器动态IP和动态映射端口问题。
```
