### ISSUE TITLE
XxlRpcProviderFactory 的 initConfig 参数建议用接口，不要用枚举

### ISSUE THREAD

**Issue by kevin82008** [xuxueli/xxl-rpc#12]
如题，XxlRpcProviderFactory 的 initConfig 参数建议用接口，不要用枚举，方便扩展其他实现

**Comment by xuxueli** [comment]
你好，感谢反馈！该建议在后续排期时会优先考虑，也欢迎提供PR啊。

**Comment by xuxueli** [comment]
你好，最新版本已经做了相关优化，可以pull master体验下。
