### ISSUE TITLE
JettyClient的BufferingResponseListener默认2M 能不能带参数传入？

### ISSUE THREAD

**Issue by baiyin1115** [xuxueli/xxl-rpc#14]
// serialize request
		byte[] requestBytes = xxlRpcReferenceBean.getSerializer().serialize(xxlRpcRequest);

        // httpclient
        HttpClient httpClient = getJettyHttpClient(xxlRpcReferenceBean.getInvokerFactory());

        // request
        Request request = httpClient.newRequest(reqURL);
        request.method(HttpMethod.POST);
        request.timeout(xxlRpcReferenceBean.getTimeout() + 500, TimeUnit.MILLISECONDS);		// async, not need timeout
        request.content(new BytesContentProvider(requestBytes));

        // invoke
        request.send(new BufferingResponseListener() {

**Comment by xuxueli** [comment]
你好，rpc场景不建议传输大数据包，会阻塞请求。如果由特殊需求，可以自行定制，也欢迎PR啊。
