### ISSUE TITLE
NettyHttpServer创建时HttpObjectAggregator这个maxContentLength最好有接口能够传入

### ISSUE THREAD

**Issue by baiyin1115** [xuxueli/xxl-rpc#15]
jetty2M，老哥我把xxljob的版本升了下，jetty换成了netty-http  你又搞个5M，虽然够用了，可架不住哪个不长眼的开发小哥会疯狂的搞日志呢。。。哎

**Comment by xuxueli** [comment]
你好，xxljob最新迭代版本会限制RollingLog长度，远远低于5M的，可以放心。

jetty和netty长度限制统一为5M了，再大的化rpc耗时会上升很快。
