### ISSUE TITLE
NettyHttpConnectClient.java 如果无法连接会持续创建NioEventLoopGroup

### ISSUE THREAD

**Issue by zhufg** [xuxueli/xxl-rpc#16]
this.channel = bootstrap.connect(host, port).sync().channel();
如果这里面连接不成功，NioEventLoopGroup不会进行释放
ConnectClient 
            ConnectClient connectClient_new = connectClientImpl.newInstance();
            connectClient_new.init(address, xxlRpcReferenceBean.getSerializer(), xxlRpcReferenceBean.getInvokerFactory());
            connectClientMap.put(address, connectClient_new);

**Comment by xuxueli** [comment]
你好，最新Release版本做了优化的，可以参考master分支代码，如下，如果连接创建失败，会主动销毁的：
```
// 代码位置：com.xxl.rpc.remoting.net.common.ConnectClient
……
ConnectClient connectClient_new = connectClientImpl.newInstance();
 try {
        connectClient_new.init(address, xxlRpcReferenceBean.getSerializer(), xxlRpcReferenceBean.getInvokerFactory());    // 初始化
        connectClientMap.put(address, connectClient_new);
} catch (Exception e) {
        connectClient_new.close();    // 销毁
        throw e;
}
……
```

**Comment by zhufg** [comment]
与release的版本有代码冲突，做了个本地的小版本，只能后续切换了
