### ISSUE TITLE
如果是JAVA提供服务，C++调用，或者反过来，怎么用呢？

### ISSUE THREAD

**Issue by liulipengju** [xuxueli/xxl-rpc#20]
跨语言调用，怎么用的

**Comment by xuxueli** [comment]
你好，跨语言可以借助提供的”泛华调用“特性实现。
XXL-RPC提供的rpc服务可借助网关转化为http服务供任意技术栈使用。
至于请求其他技术栈服务，推荐借助通用通讯协议比如http等实现。
