### ISSUE TITLE
客户端访问携带版本号的service异常问题？

### ISSUE THREAD

**Issue by vincent50411** [xuxueli/xxl-rpc#22]
server：
    service增加版本号设置，
如：@XxlRpcService(version = "1.1.1")，
注册界面key显示为：com.iflytek.medical.service.DemoApi#1.1.1

client端使用frameless模式创建测试程序：
// init client
        DemoApi2 demoService = (DemoApi2) new XxlRpcReferenceBean(NetEnum.NETTY, Serializer.SerializeEnum.HESSIAN.getSerializer(), CallType.SYNC, LoadBalance.ROUND,
                DemoApi2.class, "1.1.1", 500, "172.16.13.194:7088", null, null, null).getObject();

        String rslt = demoService.sayHello("xxxxxx", "你好啊com.iflytek.medical.service.DemoApi2");

执行后异常：
Connected to the target VM, address: '127.0.0.1:55563', transport: 'socket'
Exception in thread "main" com.xxl.rpc.util.XxlRpcException: The serviceKey[com.iflytek.medical.service.DemoApi] not found.
10:08:54.403 logback [main] INFO  c.x.r.r.i.r.XxlRpcReferenceBean - >>>>>>>>>>> xxl-rpc, invoke error, address:172.16.13.194:7088, XxlRpcRequestXxlRpcRequest{requestId='4dd8df8f-f3b2-4687-a42c-cd24b3881993', createMillisTime=1571278132458, accessToken='null', className='com.iflytek.medical.service.DemoApi', methodName='sayHello', parameterTypes=[class java.lang.String, class java.lang.String], parameters=[xxxxxx, 你好啊com.iflytek.medical.service.DemoApi2], version='null'}
	at com.xxl.rpc.remoting.invoker.reference.XxlRpcReferenceBean$1.invoke(XxlRpcReferenceBean.java:221)
	at com.sun.proxy.$Proxy0.sayHello(Unknown Source)
	at com.iflytek.medical.imeepclient.test.ClientTest.main(ClientTest.java:19)

看异常信息中，提示version='null'，但是实际initconfig时，已经设置了对应版本号信息1.1.1。
看XxlRpcReferenceBean中，构造request参数时，并没有设置version属性值：
// request
						XxlRpcRequest xxlRpcRequest = new XxlRpcRequest();
	                    xxlRpcRequest.setRequestId(UUID.randomUUID().toString());
	                    xxlRpcRequest.setCreateMillisTime(System.currentTimeMillis());
	                    xxlRpcRequest.setAccessToken(accessToken);
	                    xxlRpcRequest.setClassName(className);
	                    xxlRpcRequest.setMethodName(methodName);
	                    xxlRpcRequest.setParameterTypes(parameterTypes);
	                    xxlRpcRequest.setParameters(parameters);

==================================
修改测试代码，使用无版本号的service接口，可正常访问。

请问这是bug还是我调用的方式不对呢

**Comment by xuxueli** [comment]
你好，master分支已修复，可以pull master体验。将会跟随下个小版本发布，预计本月内发布。
