### ISSUE TITLE
xxl-rpc 调用报错

### ISSUE THREAD

**Issue by JetBrainZP** [xuxueli/xxl-rpc#23]
![image](https://user-images.githubusercontent.com/10757257/66973512-c757f080-f0ca-11e9-853b-8dc8ba876a0d.png)

请问一下，这个报错是什么意思？什么情况下会发生？
看英文的意思是发了一个空包过来，
现在在xxl-job里面经常会报这个错误，
如果把这个报错直接去掉会有什么影响？

**Comment by xuxueli** [comment]
你好，正常请求会附带请求参数，但是一些类似爬虫/端口扫描的情况会导致非法请求，触发上述报错，不影响业务。
