### ISSUE TITLE
xxl-rpc-core推送请求

### ISSUE THREAD

**Issue by longyubo** [xuxueli/xxl-rpc#3]
简化项目，烦请推送谢谢

**Comment by xuxueli** [comment]
你好，感谢反馈！
Core推送中央仓库已经加入TODO列表，将会排期跟进！

**Comment by xuxueli** [comment]
你好，感谢反馈！
Core推送中央仓库已经加入TODO列表，将会排期跟进！你好，感谢反馈！
Core推送中央仓库已经加入TODO列表，将会排期跟进！

**Comment by xuxueli** [comment]
你好，已经推送maven中央仓库，欢迎体验。
