### ISSUE TITLE
您好，请问这个项目在loadBalance这个类的match方法，应该吧item.equals(name)改成item.name().equals(name)

### ISSUE THREAD

**Issue by hduhuximing** [xuxueli/xxl-rpc#36]
public static LoadBalance match(String name, LoadBalance defaultRouter) {
        for (LoadBalance item : LoadBalance.values()) {
            if (item.equals(name)) {
                return item;
            }
        }
        return defaultRouter;
    }
改后
public static LoadBalance match(String name, LoadBalance defaultRouter) {
        for (LoadBalance item : LoadBalance.values()) {
            if (item.name().equals(name)) {
                return item;
            }
        }
        return defaultRouter;
    }

**Comment by xuxueli** [comment]
Tks，感谢反馈！已修复。
