### ISSUE TITLE
描述xxl-rpc

### ISSUE THREAD

**Issue by AndyMeng2017** [xuxueli/xxl-rpc#4]
1.请问下这个是纯个人开发的项目么？
2.和google的grpc的比较呢，更确切的说，这个项目只是初步尝试，还是经过实际线上验证，首次接触rpc，最近一直在研读此代码。
3.什么想要做这一套框架？

**Comment by xuxueli** [comment]
感谢关注！
1、社区发起的项目，目前主要我来迭代和维护；
2、相较于grpc定制型更高，多种通讯方案，http/tcp，多种序列化方案，hessian/probuff/json，等。
3、xxl-rpc 将会作为XXL系列产品的官方底层通讯选型，如xxl-job、xxl-mq等。
