### ISSUE TITLE
<img width="728" alt="xxl线程泄漏" src="https://user-images.githubusercontent.com/18181713/85251816-e0e8dd80-b48c-11ea-96c0-ce3a08058098.png">

### ISSUE THREAD

**Issue by geercode** [xuxueli/xxl-rpc#41]
<img width="728" alt="xxl线程泄漏" src="https://user-images.githubusercontent.com/18181713/85251816-e0e8dd80-b48c-11ea-96c0-ce3a08058098.png">
雪里兄好，我在使用过程中发现有线程泄漏的问题，跟这位老兄的情况比较相似，但是我还没有看到很多的代码。我使用的xxl-job版本为2.0.2，xxl-rpc是1.4.0。由于开发环境没有xxl-admin，所以在发布时间一两天后，发现了有内存溢出，full gc过于频繁的问题，一开始发现byte[] object[] char[]过多，只定位到是netty出的问题，后用jprofiler查看内存，发现有线程数过多的情况，最终定位到是xxl造成的nettygroup线程过多造成的，截图如下：
<img width="680" alt="xxl线程泄漏2" src="https://user-images.githubusercontent.com/18181713/85252456-6751ef00-b48e-11ea-869b-45ffc9cf558d.png">
后沿着注册的Exception定位到是NettyHttpConnectClient#init方法中this.channel = bootstrap.connect(host, port).sync().channel();中sync()方法失败则造成nettyGroup的channel线程失去管理。由于我没有对netty深入研究过，这个地方是否应该在更高层级对资源进行限定，channel是否也应该避免用很多线程的粗放模式。原来提这个issue的老兄跟我说的比较像，是同一个问题吗，以及现在是否已经解决？

_Originally posted by @geercode in https://github.com/xuxueli/xxl-rpc/issues/35#issuecomment-647295014_

**Comment by xuxueli** [comment]
新版本已修复，升级即可
