### ISSUE TITLE
这里问什么要搞个匿名内部类

### ISSUE THREAD

**Issue by fireflyhoo** [xuxueli/xxl-rpc#44]
https://github.com/xuxueli/xxl-rpc/blob/6ff3c03e28181bc3a186239dfb19c8788fff9b9f/xxl-rpc-core/src/main/java/com/xxl/rpc/core/remoting/net/params/Beat.java#L16

这里问什么要搞个匿名内部类,和之前的客户端版本不一致呀

**Comment by xuxueli** [comment]
for 心跳处理
