### ISSUE TITLE
注册中心--服务列表的数据为什么存三份

### ISSUE THREAD

**Issue by sunkun1210** [xuxueli/xxl-rpc#48]
选用XxlRpcAdminRegister注册中心时
服务列表的数据 客户端本地缓存存一份 db存一份 磁盘文件存一份
本地缓存和db我理解，但为什么还要在磁盘存一份
而且需要线程维护一致性
如果： 直接存一份在db里(redis)，不但减少维护一致性的代码，而且服务禁用时，请求者也不会有延迟

**Comment by yanghui-git** [comment]
单纯的为了缓存 吧，提升性能吧

xxl-rpc定位是轻量级 你还整个 db redis 那不是和 dubbo一样了，他的出发是 麻雀虽小 五脏俱全

**Comment by oceanthelh** [comment]
> 选用XxlRpcAdminRegister注册中心时
> 服务列表的数据 客户端本地缓存存一份 db存一份 磁盘文件存一份
> 本地缓存和db我理解，但为什么还要在磁盘存一份
> 而且需要线程维护一致性
> 如果： 直接存一份在db里(redis)，不但减少维护一致性的代码，而且服务禁用时，请求者也不会有延迟

个人理解，如果客户端宕机重启了且注册中心处于不可用状态就可以加载本地磁盘中的文件进行服务调用

**Comment by xuxueli** [comment]
如果客户端宕机重启了且注册中心处于不可用状态就可以加载本地磁盘中的文件进行服务调用
——————

+1
