### ISSUE TITLE
xxl-rpc-sample-client和xxl-rpc-sample-server不能直接运行的问题

### ISSUE THREAD

**Issue by caihuaxue** [xuxueli/xxl-rpc#5]
xxl-rpc-sample-client和xxl-rpc-sample-server这两个spring boot独立小模块，maven打包之后生成的jar包不能直接在linux终端中运行，原因是依赖的第三方jar不能打进去最终的jar包里面去。所以建议作者修改下这两个模块的pom.xml文件，以xxl-rpc-sample-server为例，在pom.xml里添加如下内容：

`
<build>
   <finalName>xxl-rpc-server</fileName>
  <plugins>
        <plugin>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-maven-plugin</artifactId>
            <configuration>
                 <fork>true</fork>
                 <mainClass>com.xxl.rpc.sample.server.XxlRpcServerApplication</mainClass>
            </configuration>
            <executions>
                <goals>
                      <goal>repackage</goal>
                </goals>
            </executions>
        </plugin>
  </plugins>
</build>
`
这样子最终在linux终端输入java -jar xxl-rpc-server.jar就可以直接运行起来了。

**Comment by xuxueli** [comment]
感谢反馈！springboot类型示例项目pom已更新，可以重新pull master分支体验。
