### ISSUE TITLE
请问 如何配置RpcProvider为netty呢

### ISSUE THREAD

**Issue by farsunset** [xuxueli/xxl-rpc#8]
请问 如何配置RpcProvider为netty呢，看了一圈文档里没有示例代码
http://www.xuxueli.com/xxl-rpc/#/?id=%E4%BA%8C%E3%80%81%E5%BF%AB%E9%80%9F%E5%85%A5%E9%97%A8%EF%BC%88springboot%E7%89%88%E6%9C%AC%EF%BC%89

**Comment by xuxueli** [comment]
你好，非常简单，文档搜索 “ProviderFactory 参数”，设置其参数 “netType= NETTY”，然后参考pom引入相关依赖包 （netty  + commons-pool2）即可。客户端也要做类似设置，设置 netType ，引入pom。

**Comment by farsunset** [comment]
如果执行器使用了netty 是否admin也需要修改配置使用netty呢

**Comment by farsunset** [comment]
XxlJobExecutor 和XxlRpcSpringProviderFactory 会有冲突喔 都需要配置端口
XxlJobExecutor .start方法里面会new XxlRpcInvokerFactory已经指定了是jetty

**Comment by xuxueli** [comment]
@farsunset 你好，两端通讯方案需要一致才可以，需要同时为netty。
XXL-JOB 目前版本没有将XXL-RPC的通讯方案参数开放出来，后续考虑开放出来，定制性更强一些。

一个项目支持启动多个 XXL-RPC Server的，只需要服务端口号不一致即可。
