### ISSUE TITLE
ZkServiceRegistry的refreshDiscoveryData方法existValues.addAll(childPathData.keySet())是否有误？

### ISSUE THREAD

**Issue by mnzero** [xuxueli/xxl-rpc#9]
如题。
是否应该改为existValues.addAll(childPathData.values());

**Comment by xuxueli** [comment]
你好，这是正常的，底层将服务提供方地址写到NodePath上，节点路径即服务地址。

下个版本将会提供原生注册中心，基于DB与磁盘实现，轻量级，更加方便集群扩展。届时，可以考虑迁移到原生XXL-RPC注册中心上来。
